keys:
  - &admin_domen age1pwtvmk9hhwgytkumpjxctvzyw9pledgm44qn8xjzq3s8rduy7fjqllp0nz
  - &admin_sander age138vqkmsve6sgesskmxefec22h2r0hukhlqlenq3nlgs9tuq3e9yq0xr4le
  - &server_aarch64_linux age1xs6sg06q2jj93skp6s0advfa666hjxr28c8f5egc2r3fvclwwgzst7uuk0
  - &server_x86_64_linux age166mr9pmurdrd99d0zy8m6acvnx5xje6csc4362ph67pnk6frcf6qk88nn5
  - &server_aarch64_darwin age1ndh8eamfjf7c3a0e02gs6scwp0q424t6zf2gyud582putwmy0pnqcxvrww
creation_rules:
  - path_regex: secrets\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_domen
      - *admin_sander
      - *server_aarch64_linux
      - *server_x86_64_linux
      - *server_aarch64_darwin
