name: Bump Flake inputs

on:
  schedule:
    - cron: '0 6 1,16 * *' # Twice a month (1st and 16th) at 6am.

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  bump:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23

      - name: Bump Flake inputs
        uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "Bump Flake inputs"
          pr-labels: |
            dependencies
            automated
