name: Build & Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  CACHE_NAME: cachix-ci-agents
jobs:
  build:
    strategy:
      matrix:
        os: [[self-hosted, linux], [self-hosted, macOS]]
    runs-on: ${{ matrix.os }}
    steps:
      - run: sudo rm -rf /opt&
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: "${{ env.CACHE_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build 
        run: nix -L flake check
  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: [self-hosted, linux]
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v18
      - uses: cachix/cachix-action@v12
        with:
          name: "${{ env.CACHE_NAME }}"
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: Build 
        run: nix -L build
      - name: Deploy
        env:
          CACHIX_ACTIVATE_TOKEN: "${{ secrets.CACHIX_ACTIVATE_TOKEN }}"
        # --agent is needed due to a regression in Cachix 1.1, which will be fixed in Cachix 1.2
        run: cachix deploy activate --agent linux --agent macos ./result